services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: unify_user
      POSTGRES_PASSWORD: unify_password
      POSTGRES_DB: unify_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
